package dev.medzik.hsauth;

public enum HSAuthVersion {
    /**
     * Version 1. This version uses shared secret generated by X25519.
     */
    V1(0x01);

    private final int version;

    HSAuthVersion(int version) {
        this.version = version;
    }

    public int getVersion() {
        return version;
    }
}
